#pragma once
#define VALUES_PER_VERT 8
#define NUM_TRIANGLE_VERTS 3
#define NUM_SQR_VERTS 6
#define NUM_CUBE_VERTS 36

#define NUM_LATS_SPHERE 20
#define NUM_LONGS_SPHERE 20

#define WINDOW_WIDTH 640
#define WINDOW_HEIGHT 480

#define NUM_DRAWMODES 2