/* by Aleksejs Loginovs - October 2018 */

#pragma once
#define VALUES_PER_VERT 4
#define VALUES_PER_NORMAL 3
#define NUM_TRIANGLE_VERTS 3
#define NUM_SQR_VERTS 6
#define NUM_CUBE_VERTS 36

#define NUM_LATS_SPHERE 20
#define NUM_LONGS_SPHERE 20

#define WINDOW_WIDTH 640
#define WINDOW_HEIGHT 480

#define NUM_DRAWMODES 2

#define LIGHTSOURCE_SHADER 1
#define BASIC_SHADER 2
#define SKYBOX_SHADER 3

#define CAMERA_MOVEMENT_SPEED 25.f
#define CAMERA_STRAFE_SPEED 15.f

#define LIGHT_MOVEMENT_SPEED 0.001f